# Generated by Django 3.2.4 on 2021-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=100, verbose_name='test'),
        ),
    ]
